Implement Tailscale Funnel feature

diff --git a/tailscale/rootfs/etc/services.d/tailscaled/post b/tailscale/rootfs/etc/services.d/tailscaled/post
--- a/tailscale/rootfs/etc/services.d/tailscaled/post
+++ b/tailscale/rootfs/etc/services.d/tailscaled/post
@@ -62,22 +62,94 @@ do
   sleep 1
 done
 
-# Wait for the network to be available and logged in
-while true;
+# Wait for the network to be available
+while ! /opt/tailscale status --json --peers=false --self=false \
+  | jq --exit-status '.BackendState == "Running" or .BackendState == "NeedsLogin"' > /dev/null;
 do
-  if /opt/tailscale status --json --peers=false --self=false \
-    | jq --exit-status '.BackendState == "Running" or .BackendState == "NeedsLogin"' > /dev/null;
-  then
-    IFS=","
-    /opt/tailscale up \
-      --hostname "$(bashio::info.hostname)" \
-      --advertise-exit-node \
-      --accept-routes \
-      --advertise-routes="${routes[*]}" \
-      --advertise-tags="${tags}"
-
-    bashio::exit.ok
-  fi
-  # Well... wait a bit more
   sleep 2
 done
+
+# Start Tailscale
+IFS=","
+if ! /opt/tailscale up \
+  --hostname "$(bashio::info.hostname)" \
+  --advertise-exit-node \
+  --accept-routes \
+  --advertise-routes="${routes[*]}" \
+  --advertise-tags="${tags}";
+then
+  bashio::log.error "Unable to start up Tailscale"
+  bashio::exit.nok
+fi
+
+# Wait for the network to be available and logged in
+while ! /opt/tailscale status --json --peers=false --self=false \
+  | jq --exit-status '.BackendState == "Running"' > /dev/null
+do
+  sleep 2
+done
+
+bashio::log.info "Tailscale is running"
+
+bashio::log.info "Enabling Tailscale Proxy..."
+
+declare domain
+
+# Remove previously configured proxy first, because the configuration is persistent between reboots
+/opt/tailscale serve --remove / &> /dev/null || true
+
+# Checking if SSL is used
+if bashio::var.true "$(bashio::core.ssl)"; then
+  bashio::log.warning
+  bashio::log.warning "Home Assistant is not accessible through plain http connection."
+  bashio::log.warning "See the 'Prerequisites chapter' in the add-on's Documentation."
+  bashio::log.warning
+  bashio::log.warning ">>> CHANGE CONFIGURATION AND THEN RESTART THIS ADD-ON!!! <<<"
+  bashio::log.warning
+  bashio::exit.ok
+fi
+
+# Check if Tailscale HTTPS is enabled
+if ! /opt/tailscale status --self=true --peers=false --json \
+  | jq -rce ".CertDomains[0]" > /dev/null;
+then
+  bashio::log.warning
+  bashio::log.warning "Can't get your Tailscale domain, is Tailscale's HTTPS support enabled?"
+  bashio::log.warning "See the 'Prerequisites chapter' in the add-on's Documentation."
+  bashio::log.warning
+  bashio::log.warning ">>> CHANGE CONFIGURATION AND THEN RESTART THIS ADD-ON!!! <<<"
+  bashio::log.warning
+  bashio::exit.ok
+fi
+domain=$(/opt/tailscale status --self=true --peers=false --json | jq -rc ".CertDomains[0]")
+
+# Set up proxy
+if ! /opt/tailscale serve / proxy http://localhost:$(bashio::core.port); then
+  bashio::log.error "Unable to configure Tailscale Proxy"
+  bashio::exit.nok
+fi
+bashio::log.info "Tailscale Proxy is enabled:"
+bashio::log.info "  Your Home Assistant instance is available within your Tailnet VPN at"
+bashio::log.info "  https://${domain}"
+
+bashio::log.info "Enabling Tailscale Funnel..."
+
+# Check if funnel is available
+if ! /opt/tailscale serve funnel off; then
+  bashio::log.warning
+  bashio::log.warning "Funnel is not available, is Funnel feature enabled?"
+  bashio::log.warning "See the 'Required Tailscale configuration' chapter in the add-on's Documentation."
+  bashio::log.warning
+  bashio::log.warning ">>> CHANGE CONFIGURATION AND THEN RESTART THIS ADD-ON!!! <<<"
+  bashio::log.warning
+  bashio::exit.ok
+fi
+
+# Set up funnel
+if ! /opt/tailscale serve funnel on; then
+  bashio::log.error "Unable to configure Tailscale Funnel"
+  bashio::exit.nok
+fi
+bashio::log.info "Tailscale Funnel is enabled:"
+bashio::log.info "  Your Homeassistant instance is publicly available on the internet at"
+bashio::log.info "  https://${domain}"
